/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as R403RouteImport } from './routes/403'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminNoticesRouteImport } from './routes/_admin/notices'
import { Route as AdminMembersRouteImport } from './routes/_admin/members'
import { Route as AdminNoticesIndexRouteImport } from './routes/_admin/notices/index'
import { Route as AdminNoticesNewRouteImport } from './routes/_admin/notices/new'
import { Route as AdminNoticesNoticeIdRouteImport } from './routes/_admin/notices/$noticeId'
import { Route as AdminNoticesNoticeIdIndexRouteImport } from './routes/_admin/notices/$noticeId/index'
import { Route as AdminNoticesNoticeIdEditRouteImport } from './routes/_admin/notices/$noticeId/edit'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesIndexRoute = AdminNoticesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminNoticesRoute,
} as any)
const AdminNoticesNewRoute = AdminNoticesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminNoticesRoute,
} as any)
const AdminNoticesNoticeIdRoute = AdminNoticesNoticeIdRouteImport.update({
  id: '/$noticeId',
  path: '/$noticeId',
  getParentRoute: () => AdminNoticesRoute,
} as any)
const AdminNoticesNoticeIdIndexRoute =
  AdminNoticesNoticeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminNoticesNoticeIdRoute,
  } as any)
const AdminNoticesNoticeIdEditRoute =
  AdminNoticesNoticeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminNoticesNoticeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/403': typeof R403Route
  '/members': typeof AdminMembersRoute
  '/notices': typeof AdminNoticesRouteWithChildren
  '/': typeof AdminIndexRoute
  '/notices/$noticeId': typeof AdminNoticesNoticeIdRouteWithChildren
  '/notices/new': typeof AdminNoticesNewRoute
  '/notices/': typeof AdminNoticesIndexRoute
  '/notices/$noticeId/edit': typeof AdminNoticesNoticeIdEditRoute
  '/notices/$noticeId/': typeof AdminNoticesNoticeIdIndexRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/members': typeof AdminMembersRoute
  '/': typeof AdminIndexRoute
  '/notices/new': typeof AdminNoticesNewRoute
  '/notices': typeof AdminNoticesIndexRoute
  '/notices/$noticeId/edit': typeof AdminNoticesNoticeIdEditRoute
  '/notices/$noticeId': typeof AdminNoticesNoticeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/403': typeof R403Route
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/members': typeof AdminMembersRoute
  '/_admin/notices': typeof AdminNoticesRouteWithChildren
  '/_admin/': typeof AdminIndexRoute
  '/_admin/notices/$noticeId': typeof AdminNoticesNoticeIdRouteWithChildren
  '/_admin/notices/new': typeof AdminNoticesNewRoute
  '/_admin/notices/': typeof AdminNoticesIndexRoute
  '/_admin/notices/$noticeId/edit': typeof AdminNoticesNoticeIdEditRoute
  '/_admin/notices/$noticeId/': typeof AdminNoticesNoticeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/403'
    | '/members'
    | '/notices'
    | '/'
    | '/notices/$noticeId'
    | '/notices/new'
    | '/notices/'
    | '/notices/$noticeId/edit'
    | '/notices/$noticeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/members'
    | '/'
    | '/notices/new'
    | '/notices'
    | '/notices/$noticeId/edit'
    | '/notices/$noticeId'
  id:
    | '__root__'
    | '/403'
    | '/_admin'
    | '/_admin/members'
    | '/_admin/notices'
    | '/_admin/'
    | '/_admin/notices/$noticeId'
    | '/_admin/notices/new'
    | '/_admin/notices/'
    | '/_admin/notices/$noticeId/edit'
    | '/_admin/notices/$noticeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R403Route: typeof R403Route
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notices': {
      id: '/_admin/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/members': {
      id: '/_admin/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notices/': {
      id: '/_admin/notices/'
      path: '/'
      fullPath: '/notices/'
      preLoaderRoute: typeof AdminNoticesIndexRouteImport
      parentRoute: typeof AdminNoticesRoute
    }
    '/_admin/notices/new': {
      id: '/_admin/notices/new'
      path: '/new'
      fullPath: '/notices/new'
      preLoaderRoute: typeof AdminNoticesNewRouteImport
      parentRoute: typeof AdminNoticesRoute
    }
    '/_admin/notices/$noticeId': {
      id: '/_admin/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof AdminNoticesNoticeIdRouteImport
      parentRoute: typeof AdminNoticesRoute
    }
    '/_admin/notices/$noticeId/': {
      id: '/_admin/notices/$noticeId/'
      path: '/'
      fullPath: '/notices/$noticeId/'
      preLoaderRoute: typeof AdminNoticesNoticeIdIndexRouteImport
      parentRoute: typeof AdminNoticesNoticeIdRoute
    }
    '/_admin/notices/$noticeId/edit': {
      id: '/_admin/notices/$noticeId/edit'
      path: '/edit'
      fullPath: '/notices/$noticeId/edit'
      preLoaderRoute: typeof AdminNoticesNoticeIdEditRouteImport
      parentRoute: typeof AdminNoticesNoticeIdRoute
    }
  }
}

interface AdminNoticesNoticeIdRouteChildren {
  AdminNoticesNoticeIdEditRoute: typeof AdminNoticesNoticeIdEditRoute
  AdminNoticesNoticeIdIndexRoute: typeof AdminNoticesNoticeIdIndexRoute
}

const AdminNoticesNoticeIdRouteChildren: AdminNoticesNoticeIdRouteChildren = {
  AdminNoticesNoticeIdEditRoute: AdminNoticesNoticeIdEditRoute,
  AdminNoticesNoticeIdIndexRoute: AdminNoticesNoticeIdIndexRoute,
}

const AdminNoticesNoticeIdRouteWithChildren =
  AdminNoticesNoticeIdRoute._addFileChildren(AdminNoticesNoticeIdRouteChildren)

interface AdminNoticesRouteChildren {
  AdminNoticesNoticeIdRoute: typeof AdminNoticesNoticeIdRouteWithChildren
  AdminNoticesNewRoute: typeof AdminNoticesNewRoute
  AdminNoticesIndexRoute: typeof AdminNoticesIndexRoute
}

const AdminNoticesRouteChildren: AdminNoticesRouteChildren = {
  AdminNoticesNoticeIdRoute: AdminNoticesNoticeIdRouteWithChildren,
  AdminNoticesNewRoute: AdminNoticesNewRoute,
  AdminNoticesIndexRoute: AdminNoticesIndexRoute,
}

const AdminNoticesRouteWithChildren = AdminNoticesRoute._addFileChildren(
  AdminNoticesRouteChildren,
)

interface AdminRouteChildren {
  AdminMembersRoute: typeof AdminMembersRoute
  AdminNoticesRoute: typeof AdminNoticesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMembersRoute: AdminMembersRoute,
  AdminNoticesRoute: AdminNoticesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R403Route: R403Route,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
