export const STIBEE_DOMAIN = 'page.stibee.com';
export const MAILY_DOMAIN = 'maily.so';

export const NEWSLETTER_DETAIL_MAIN_WIDTH = 700;
export const NEWSLETTER_DETAIL_SIDE_WIDTH = 320;
export const NEWSLETTER_DETAIL_SIDE_GAP = 24;
export const NEWSLETTER_DETAIL_SIDE_VISIBLE_MIN_WIDTH =
  NEWSLETTER_DETAIL_MAIN_WIDTH +
  (NEWSLETTER_DETAIL_SIDE_WIDTH + NEWSLETTER_DETAIL_SIDE_GAP) * 2;
