/* eslint-disable */
/**
 * @generated by @bombom/oas-gen
 * Do not edit by hand — run `pnpm web:generate-openapi-types`.
 */
import { fetcher } from '@bombom/shared/apis';
import type { operations } from '@/types/openapi-spec';

export type GetPetResponse = NonNullable<
  operations['getPet']['responses']['200']['content']['application/json']
>;

export const getPet = async () => {
  return fetcher.get<GetPetResponse>({ path: '/members/me/pet' });
};

export const attend = async () => {
  return fetcher.post<never, void>({ path: '/members/me/pet/attendance' });
};
