/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ContentsContentIdAnswerRouteImport } from './routes/contents/$contentId/answer';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ContentsContentIdAnswerRoute = ContentsContentIdAnswerRouteImport.update({
  id: '/contents/$contentId/answer',
  path: '/contents/$contentId/answer',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/signup': typeof SignupRoute;
  '/contents/$contentId/answer': typeof ContentsContentIdAnswerRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/signup': typeof SignupRoute;
  '/contents/$contentId/answer': typeof ContentsContentIdAnswerRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/signup': typeof SignupRoute;
  '/contents/$contentId/answer': typeof ContentsContentIdAnswerRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/signup' | '/contents/$contentId/answer';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/signup' | '/contents/$contentId/answer';
  id: '__root__' | '/' | '/signup' | '/contents/$contentId/answer';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SignupRoute: typeof SignupRoute;
  ContentsContentIdAnswerRoute: typeof ContentsContentIdAnswerRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/contents/$contentId/answer': {
      id: '/contents/$contentId/answer';
      path: '/contents/$contentId/answer';
      fullPath: '/contents/$contentId/answer';
      preLoaderRoute: typeof ContentsContentIdAnswerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignupRoute: SignupRoute,
  ContentsContentIdAnswerRoute: ContentsContentIdAnswerRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
