name: 'Discord Notify'
description: 'Send Discord webhook'

inputs:
  webhook:
    required: true
  title:
    required: true
  url:
    required: true
  content:
    required: true
  mentions:
    required: true
  color:
    required: false
    default: '15158332'
  fields:
    required: false
    default: '[]'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        # fields(JSON 배열)를 inline=true 포함 형태로 변환
        RAW_FIELDS='${{ inputs.fields }}'

        # JSON 변환을 위해 jq 설치 (ubuntu-latest 기본 포함)
        FINAL_FIELDS=$(echo "$RAW_FIELDS" | jq '
          map(. + {inline: true})
        ')

        curl -X POST \
          -H "Content-Type: application/json" \
          -d "{
            \"username\": \"FE Bot\",
            \"content\": \"${{ inputs.content }}\n${{ inputs.mentions }}\",
            \"embeds\": [
              {
                \"title\": \"${{ inputs.title }}\",
                \"url\": \"${{ inputs.url }}\",
                \"color\": ${{ inputs.color }},
                \"fields\": $FINAL_FIELDS,
                \"footer\": { \"text\": \"자동 알림 메시지입니다\" }
              }
            ]
          }" \
          "${{ inputs.webhook }}"
