/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as MaintenanceRouteImport } from './routes/maintenance';
import { Route as LoginRouteImport } from './routes/login';
import { Route as LandingRouteImport } from './routes/landing';
import { Route as BombomRouteImport } from './routes/_bombom';
import { Route as BombomMainRouteImport } from './routes/_bombom/_main';
import { Route as BombomMainIndexRouteImport } from './routes/_bombom/_main/index';
import { Route as BombomArticlesArticleIdRouteImport } from './routes/_bombom/articles.$articleId';
import { Route as BombomMainTodayRouteImport } from './routes/_bombom/_main/today';
import { Route as BombomMainStorageRouteImport } from './routes/_bombom/_main/storage';
import { Route as BombomMainNoticeRouteImport } from './routes/_bombom/_main/notice';
import { Route as BombomMainMyRouteImport } from './routes/_bombom/_main/my';
import { Route as BombomMainMemoRouteImport } from './routes/_bombom/_main/memo';
import { Route as BombomMainGuideRouteImport } from './routes/_bombom/_main/guide';
import { Route as BombomMainChallengeRouteImport } from './routes/_bombom/_main/challenge';
import { Route as BombomMainBookmarkRouteImport } from './routes/_bombom/_main/bookmark';
import { Route as BombomMainChallengeIndexRouteImport } from './routes/_bombom/_main/challenge/index';
import { Route as BombomArticlesPreviousArticleIdRouteImport } from './routes/_bombom/articles.previous.$articleId';
import { Route as BombomArticlesGuideGuideIdRouteImport } from './routes/_bombom/articles.guide.$guideId';
import { Route as BombomMainChallengeChallengeIdRouteImport } from './routes/_bombom/_main/challenge/$challengeId';
import { Route as BombomMainChallengeChallengeIdIndexRouteImport } from './routes/_bombom/_main/challenge/$challengeId/index';
import { Route as BombomMainChallengeChallengeIdDashboardRouteImport } from './routes/_bombom/_main/challenge/$challengeId/dashboard';
import { Route as BombomMainChallengeChallengeIdDailyRouteImport } from './routes/_bombom/_main/challenge/$challengeId/daily';
import { Route as BombomMainChallengeChallengeIdCommentsRouteImport } from './routes/_bombom/_main/challenge/$challengeId/comments';
import { Route as BombomMainChallengeChallengeIdCertificationRouteImport } from './routes/_bombom/_main/challenge/$challengeId/certification';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any);
const BombomRoute = BombomRouteImport.update({
  id: '/_bombom',
  getParentRoute: () => rootRouteImport,
} as any);
const BombomMainRoute = BombomMainRouteImport.update({
  id: '/_main',
  getParentRoute: () => BombomRoute,
} as any);
const BombomMainIndexRoute = BombomMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BombomMainRoute,
} as any);
const BombomArticlesArticleIdRoute = BombomArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => BombomRoute,
} as any);
const BombomMainTodayRoute = BombomMainTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => BombomMainRoute,
} as any);
const BombomMainStorageRoute = BombomMainStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => BombomMainRoute,
} as any);
const BombomMainNoticeRoute = BombomMainNoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => BombomMainRoute,
} as any);
const BombomMainMyRoute = BombomMainMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => BombomMainRoute,
} as any);
const BombomMainMemoRoute = BombomMainMemoRouteImport.update({
  id: '/memo',
  path: '/memo',
  getParentRoute: () => BombomMainRoute,
} as any);
const BombomMainGuideRoute = BombomMainGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => BombomMainRoute,
} as any);
const BombomMainChallengeRoute = BombomMainChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => BombomMainRoute,
} as any);
const BombomMainBookmarkRoute = BombomMainBookmarkRouteImport.update({
  id: '/bookmark',
  path: '/bookmark',
  getParentRoute: () => BombomMainRoute,
} as any);
const BombomMainChallengeIndexRoute =
  BombomMainChallengeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BombomMainChallengeRoute,
  } as any);
const BombomArticlesPreviousArticleIdRoute =
  BombomArticlesPreviousArticleIdRouteImport.update({
    id: '/articles/previous/$articleId',
    path: '/articles/previous/$articleId',
    getParentRoute: () => BombomRoute,
  } as any);
const BombomArticlesGuideGuideIdRoute =
  BombomArticlesGuideGuideIdRouteImport.update({
    id: '/articles/guide/$guideId',
    path: '/articles/guide/$guideId',
    getParentRoute: () => BombomRoute,
  } as any);
const BombomMainChallengeChallengeIdRoute =
  BombomMainChallengeChallengeIdRouteImport.update({
    id: '/$challengeId',
    path: '/$challengeId',
    getParentRoute: () => BombomMainChallengeRoute,
  } as any);
const BombomMainChallengeChallengeIdIndexRoute =
  BombomMainChallengeChallengeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BombomMainChallengeChallengeIdRoute,
  } as any);
const BombomMainChallengeChallengeIdDashboardRoute =
  BombomMainChallengeChallengeIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => BombomMainChallengeChallengeIdRoute,
  } as any);
const BombomMainChallengeChallengeIdDailyRoute =
  BombomMainChallengeChallengeIdDailyRouteImport.update({
    id: '/daily',
    path: '/daily',
    getParentRoute: () => BombomMainChallengeChallengeIdRoute,
  } as any);
const BombomMainChallengeChallengeIdCommentsRoute =
  BombomMainChallengeChallengeIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => BombomMainChallengeChallengeIdRoute,
  } as any);
const BombomMainChallengeChallengeIdCertificationRoute =
  BombomMainChallengeChallengeIdCertificationRouteImport.update({
    id: '/certification',
    path: '/certification',
    getParentRoute: () => BombomMainChallengeChallengeIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/landing': typeof LandingRoute;
  '/login': typeof LoginRoute;
  '/maintenance': typeof MaintenanceRoute;
  '/signup': typeof SignupRoute;
  '/bookmark': typeof BombomMainBookmarkRoute;
  '/challenge': typeof BombomMainChallengeRouteWithChildren;
  '/guide': typeof BombomMainGuideRoute;
  '/memo': typeof BombomMainMemoRoute;
  '/my': typeof BombomMainMyRoute;
  '/notice': typeof BombomMainNoticeRoute;
  '/storage': typeof BombomMainStorageRoute;
  '/today': typeof BombomMainTodayRoute;
  '/articles/$articleId': typeof BombomArticlesArticleIdRoute;
  '/': typeof BombomMainIndexRoute;
  '/challenge/$challengeId': typeof BombomMainChallengeChallengeIdRouteWithChildren;
  '/articles/guide/$guideId': typeof BombomArticlesGuideGuideIdRoute;
  '/articles/previous/$articleId': typeof BombomArticlesPreviousArticleIdRoute;
  '/challenge/': typeof BombomMainChallengeIndexRoute;
  '/challenge/$challengeId/certification': typeof BombomMainChallengeChallengeIdCertificationRoute;
  '/challenge/$challengeId/comments': typeof BombomMainChallengeChallengeIdCommentsRoute;
  '/challenge/$challengeId/daily': typeof BombomMainChallengeChallengeIdDailyRoute;
  '/challenge/$challengeId/dashboard': typeof BombomMainChallengeChallengeIdDashboardRoute;
  '/challenge/$challengeId/': typeof BombomMainChallengeChallengeIdIndexRoute;
}
export interface FileRoutesByTo {
  '/landing': typeof LandingRoute;
  '/login': typeof LoginRoute;
  '/maintenance': typeof MaintenanceRoute;
  '/signup': typeof SignupRoute;
  '/bookmark': typeof BombomMainBookmarkRoute;
  '/guide': typeof BombomMainGuideRoute;
  '/memo': typeof BombomMainMemoRoute;
  '/my': typeof BombomMainMyRoute;
  '/notice': typeof BombomMainNoticeRoute;
  '/storage': typeof BombomMainStorageRoute;
  '/today': typeof BombomMainTodayRoute;
  '/articles/$articleId': typeof BombomArticlesArticleIdRoute;
  '/': typeof BombomMainIndexRoute;
  '/articles/guide/$guideId': typeof BombomArticlesGuideGuideIdRoute;
  '/articles/previous/$articleId': typeof BombomArticlesPreviousArticleIdRoute;
  '/challenge': typeof BombomMainChallengeIndexRoute;
  '/challenge/$challengeId/certification': typeof BombomMainChallengeChallengeIdCertificationRoute;
  '/challenge/$challengeId/comments': typeof BombomMainChallengeChallengeIdCommentsRoute;
  '/challenge/$challengeId/daily': typeof BombomMainChallengeChallengeIdDailyRoute;
  '/challenge/$challengeId/dashboard': typeof BombomMainChallengeChallengeIdDashboardRoute;
  '/challenge/$challengeId': typeof BombomMainChallengeChallengeIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_bombom': typeof BombomRouteWithChildren;
  '/landing': typeof LandingRoute;
  '/login': typeof LoginRoute;
  '/maintenance': typeof MaintenanceRoute;
  '/signup': typeof SignupRoute;
  '/_bombom/_main': typeof BombomMainRouteWithChildren;
  '/_bombom/_main/bookmark': typeof BombomMainBookmarkRoute;
  '/_bombom/_main/challenge': typeof BombomMainChallengeRouteWithChildren;
  '/_bombom/_main/guide': typeof BombomMainGuideRoute;
  '/_bombom/_main/memo': typeof BombomMainMemoRoute;
  '/_bombom/_main/my': typeof BombomMainMyRoute;
  '/_bombom/_main/notice': typeof BombomMainNoticeRoute;
  '/_bombom/_main/storage': typeof BombomMainStorageRoute;
  '/_bombom/_main/today': typeof BombomMainTodayRoute;
  '/_bombom/articles/$articleId': typeof BombomArticlesArticleIdRoute;
  '/_bombom/_main/': typeof BombomMainIndexRoute;
  '/_bombom/_main/challenge/$challengeId': typeof BombomMainChallengeChallengeIdRouteWithChildren;
  '/_bombom/articles/guide/$guideId': typeof BombomArticlesGuideGuideIdRoute;
  '/_bombom/articles/previous/$articleId': typeof BombomArticlesPreviousArticleIdRoute;
  '/_bombom/_main/challenge/': typeof BombomMainChallengeIndexRoute;
  '/_bombom/_main/challenge/$challengeId/certification': typeof BombomMainChallengeChallengeIdCertificationRoute;
  '/_bombom/_main/challenge/$challengeId/comments': typeof BombomMainChallengeChallengeIdCommentsRoute;
  '/_bombom/_main/challenge/$challengeId/daily': typeof BombomMainChallengeChallengeIdDailyRoute;
  '/_bombom/_main/challenge/$challengeId/dashboard': typeof BombomMainChallengeChallengeIdDashboardRoute;
  '/_bombom/_main/challenge/$challengeId/': typeof BombomMainChallengeChallengeIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/landing'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/bookmark'
    | '/challenge'
    | '/guide'
    | '/memo'
    | '/my'
    | '/notice'
    | '/storage'
    | '/today'
    | '/articles/$articleId'
    | '/'
    | '/challenge/$challengeId'
    | '/articles/guide/$guideId'
    | '/articles/previous/$articleId'
    | '/challenge/'
    | '/challenge/$challengeId/certification'
    | '/challenge/$challengeId/comments'
    | '/challenge/$challengeId/daily'
    | '/challenge/$challengeId/dashboard'
    | '/challenge/$challengeId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/landing'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/bookmark'
    | '/guide'
    | '/memo'
    | '/my'
    | '/notice'
    | '/storage'
    | '/today'
    | '/articles/$articleId'
    | '/'
    | '/articles/guide/$guideId'
    | '/articles/previous/$articleId'
    | '/challenge'
    | '/challenge/$challengeId/certification'
    | '/challenge/$challengeId/comments'
    | '/challenge/$challengeId/daily'
    | '/challenge/$challengeId/dashboard'
    | '/challenge/$challengeId';
  id:
    | '__root__'
    | '/_bombom'
    | '/landing'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/_bombom/_main'
    | '/_bombom/_main/bookmark'
    | '/_bombom/_main/challenge'
    | '/_bombom/_main/guide'
    | '/_bombom/_main/memo'
    | '/_bombom/_main/my'
    | '/_bombom/_main/notice'
    | '/_bombom/_main/storage'
    | '/_bombom/_main/today'
    | '/_bombom/articles/$articleId'
    | '/_bombom/_main/'
    | '/_bombom/_main/challenge/$challengeId'
    | '/_bombom/articles/guide/$guideId'
    | '/_bombom/articles/previous/$articleId'
    | '/_bombom/_main/challenge/'
    | '/_bombom/_main/challenge/$challengeId/certification'
    | '/_bombom/_main/challenge/$challengeId/comments'
    | '/_bombom/_main/challenge/$challengeId/daily'
    | '/_bombom/_main/challenge/$challengeId/dashboard'
    | '/_bombom/_main/challenge/$challengeId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  BombomRoute: typeof BombomRouteWithChildren;
  LandingRoute: typeof LandingRoute;
  LoginRoute: typeof LoginRoute;
  MaintenanceRoute: typeof MaintenanceRoute;
  SignupRoute: typeof SignupRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/maintenance': {
      id: '/maintenance';
      path: '/maintenance';
      fullPath: '/maintenance';
      preLoaderRoute: typeof MaintenanceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/landing': {
      id: '/landing';
      path: '/landing';
      fullPath: '/landing';
      preLoaderRoute: typeof LandingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_bombom': {
      id: '/_bombom';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof BombomRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_bombom/_main': {
      id: '/_bombom/_main';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof BombomMainRouteImport;
      parentRoute: typeof BombomRoute;
    };
    '/_bombom/_main/': {
      id: '/_bombom/_main/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof BombomMainIndexRouteImport;
      parentRoute: typeof BombomMainRoute;
    };
    '/_bombom/articles/$articleId': {
      id: '/_bombom/articles/$articleId';
      path: '/articles/$articleId';
      fullPath: '/articles/$articleId';
      preLoaderRoute: typeof BombomArticlesArticleIdRouteImport;
      parentRoute: typeof BombomRoute;
    };
    '/_bombom/_main/today': {
      id: '/_bombom/_main/today';
      path: '/today';
      fullPath: '/today';
      preLoaderRoute: typeof BombomMainTodayRouteImport;
      parentRoute: typeof BombomMainRoute;
    };
    '/_bombom/_main/storage': {
      id: '/_bombom/_main/storage';
      path: '/storage';
      fullPath: '/storage';
      preLoaderRoute: typeof BombomMainStorageRouteImport;
      parentRoute: typeof BombomMainRoute;
    };
    '/_bombom/_main/notice': {
      id: '/_bombom/_main/notice';
      path: '/notice';
      fullPath: '/notice';
      preLoaderRoute: typeof BombomMainNoticeRouteImport;
      parentRoute: typeof BombomMainRoute;
    };
    '/_bombom/_main/my': {
      id: '/_bombom/_main/my';
      path: '/my';
      fullPath: '/my';
      preLoaderRoute: typeof BombomMainMyRouteImport;
      parentRoute: typeof BombomMainRoute;
    };
    '/_bombom/_main/memo': {
      id: '/_bombom/_main/memo';
      path: '/memo';
      fullPath: '/memo';
      preLoaderRoute: typeof BombomMainMemoRouteImport;
      parentRoute: typeof BombomMainRoute;
    };
    '/_bombom/_main/guide': {
      id: '/_bombom/_main/guide';
      path: '/guide';
      fullPath: '/guide';
      preLoaderRoute: typeof BombomMainGuideRouteImport;
      parentRoute: typeof BombomMainRoute;
    };
    '/_bombom/_main/challenge': {
      id: '/_bombom/_main/challenge';
      path: '/challenge';
      fullPath: '/challenge';
      preLoaderRoute: typeof BombomMainChallengeRouteImport;
      parentRoute: typeof BombomMainRoute;
    };
    '/_bombom/_main/bookmark': {
      id: '/_bombom/_main/bookmark';
      path: '/bookmark';
      fullPath: '/bookmark';
      preLoaderRoute: typeof BombomMainBookmarkRouteImport;
      parentRoute: typeof BombomMainRoute;
    };
    '/_bombom/_main/challenge/': {
      id: '/_bombom/_main/challenge/';
      path: '/';
      fullPath: '/challenge/';
      preLoaderRoute: typeof BombomMainChallengeIndexRouteImport;
      parentRoute: typeof BombomMainChallengeRoute;
    };
    '/_bombom/articles/previous/$articleId': {
      id: '/_bombom/articles/previous/$articleId';
      path: '/articles/previous/$articleId';
      fullPath: '/articles/previous/$articleId';
      preLoaderRoute: typeof BombomArticlesPreviousArticleIdRouteImport;
      parentRoute: typeof BombomRoute;
    };
    '/_bombom/articles/guide/$guideId': {
      id: '/_bombom/articles/guide/$guideId';
      path: '/articles/guide/$guideId';
      fullPath: '/articles/guide/$guideId';
      preLoaderRoute: typeof BombomArticlesGuideGuideIdRouteImport;
      parentRoute: typeof BombomRoute;
    };
    '/_bombom/_main/challenge/$challengeId': {
      id: '/_bombom/_main/challenge/$challengeId';
      path: '/$challengeId';
      fullPath: '/challenge/$challengeId';
      preLoaderRoute: typeof BombomMainChallengeChallengeIdRouteImport;
      parentRoute: typeof BombomMainChallengeRoute;
    };
    '/_bombom/_main/challenge/$challengeId/': {
      id: '/_bombom/_main/challenge/$challengeId/';
      path: '/';
      fullPath: '/challenge/$challengeId/';
      preLoaderRoute: typeof BombomMainChallengeChallengeIdIndexRouteImport;
      parentRoute: typeof BombomMainChallengeChallengeIdRoute;
    };
    '/_bombom/_main/challenge/$challengeId/dashboard': {
      id: '/_bombom/_main/challenge/$challengeId/dashboard';
      path: '/dashboard';
      fullPath: '/challenge/$challengeId/dashboard';
      preLoaderRoute: typeof BombomMainChallengeChallengeIdDashboardRouteImport;
      parentRoute: typeof BombomMainChallengeChallengeIdRoute;
    };
    '/_bombom/_main/challenge/$challengeId/daily': {
      id: '/_bombom/_main/challenge/$challengeId/daily';
      path: '/daily';
      fullPath: '/challenge/$challengeId/daily';
      preLoaderRoute: typeof BombomMainChallengeChallengeIdDailyRouteImport;
      parentRoute: typeof BombomMainChallengeChallengeIdRoute;
    };
    '/_bombom/_main/challenge/$challengeId/comments': {
      id: '/_bombom/_main/challenge/$challengeId/comments';
      path: '/comments';
      fullPath: '/challenge/$challengeId/comments';
      preLoaderRoute: typeof BombomMainChallengeChallengeIdCommentsRouteImport;
      parentRoute: typeof BombomMainChallengeChallengeIdRoute;
    };
    '/_bombom/_main/challenge/$challengeId/certification': {
      id: '/_bombom/_main/challenge/$challengeId/certification';
      path: '/certification';
      fullPath: '/challenge/$challengeId/certification';
      preLoaderRoute: typeof BombomMainChallengeChallengeIdCertificationRouteImport;
      parentRoute: typeof BombomMainChallengeChallengeIdRoute;
    };
  }
}

interface BombomMainChallengeChallengeIdRouteChildren {
  BombomMainChallengeChallengeIdCertificationRoute: typeof BombomMainChallengeChallengeIdCertificationRoute;
  BombomMainChallengeChallengeIdCommentsRoute: typeof BombomMainChallengeChallengeIdCommentsRoute;
  BombomMainChallengeChallengeIdDailyRoute: typeof BombomMainChallengeChallengeIdDailyRoute;
  BombomMainChallengeChallengeIdDashboardRoute: typeof BombomMainChallengeChallengeIdDashboardRoute;
  BombomMainChallengeChallengeIdIndexRoute: typeof BombomMainChallengeChallengeIdIndexRoute;
}

const BombomMainChallengeChallengeIdRouteChildren: BombomMainChallengeChallengeIdRouteChildren =
  {
    BombomMainChallengeChallengeIdCertificationRoute:
      BombomMainChallengeChallengeIdCertificationRoute,
    BombomMainChallengeChallengeIdCommentsRoute:
      BombomMainChallengeChallengeIdCommentsRoute,
    BombomMainChallengeChallengeIdDailyRoute:
      BombomMainChallengeChallengeIdDailyRoute,
    BombomMainChallengeChallengeIdDashboardRoute:
      BombomMainChallengeChallengeIdDashboardRoute,
    BombomMainChallengeChallengeIdIndexRoute:
      BombomMainChallengeChallengeIdIndexRoute,
  };

const BombomMainChallengeChallengeIdRouteWithChildren =
  BombomMainChallengeChallengeIdRoute._addFileChildren(
    BombomMainChallengeChallengeIdRouteChildren,
  );

interface BombomMainChallengeRouteChildren {
  BombomMainChallengeChallengeIdRoute: typeof BombomMainChallengeChallengeIdRouteWithChildren;
  BombomMainChallengeIndexRoute: typeof BombomMainChallengeIndexRoute;
}

const BombomMainChallengeRouteChildren: BombomMainChallengeRouteChildren = {
  BombomMainChallengeChallengeIdRoute:
    BombomMainChallengeChallengeIdRouteWithChildren,
  BombomMainChallengeIndexRoute: BombomMainChallengeIndexRoute,
};

const BombomMainChallengeRouteWithChildren =
  BombomMainChallengeRoute._addFileChildren(BombomMainChallengeRouteChildren);

interface BombomMainRouteChildren {
  BombomMainBookmarkRoute: typeof BombomMainBookmarkRoute;
  BombomMainChallengeRoute: typeof BombomMainChallengeRouteWithChildren;
  BombomMainGuideRoute: typeof BombomMainGuideRoute;
  BombomMainMemoRoute: typeof BombomMainMemoRoute;
  BombomMainMyRoute: typeof BombomMainMyRoute;
  BombomMainNoticeRoute: typeof BombomMainNoticeRoute;
  BombomMainStorageRoute: typeof BombomMainStorageRoute;
  BombomMainTodayRoute: typeof BombomMainTodayRoute;
  BombomMainIndexRoute: typeof BombomMainIndexRoute;
}

const BombomMainRouteChildren: BombomMainRouteChildren = {
  BombomMainBookmarkRoute: BombomMainBookmarkRoute,
  BombomMainChallengeRoute: BombomMainChallengeRouteWithChildren,
  BombomMainGuideRoute: BombomMainGuideRoute,
  BombomMainMemoRoute: BombomMainMemoRoute,
  BombomMainMyRoute: BombomMainMyRoute,
  BombomMainNoticeRoute: BombomMainNoticeRoute,
  BombomMainStorageRoute: BombomMainStorageRoute,
  BombomMainTodayRoute: BombomMainTodayRoute,
  BombomMainIndexRoute: BombomMainIndexRoute,
};

const BombomMainRouteWithChildren = BombomMainRoute._addFileChildren(
  BombomMainRouteChildren,
);

interface BombomRouteChildren {
  BombomMainRoute: typeof BombomMainRouteWithChildren;
  BombomArticlesArticleIdRoute: typeof BombomArticlesArticleIdRoute;
  BombomArticlesGuideGuideIdRoute: typeof BombomArticlesGuideGuideIdRoute;
  BombomArticlesPreviousArticleIdRoute: typeof BombomArticlesPreviousArticleIdRoute;
}

const BombomRouteChildren: BombomRouteChildren = {
  BombomMainRoute: BombomMainRouteWithChildren,
  BombomArticlesArticleIdRoute: BombomArticlesArticleIdRoute,
  BombomArticlesGuideGuideIdRoute: BombomArticlesGuideGuideIdRoute,
  BombomArticlesPreviousArticleIdRoute: BombomArticlesPreviousArticleIdRoute,
};

const BombomRouteWithChildren =
  BombomRoute._addFileChildren(BombomRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  BombomRoute: BombomRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  SignupRoute: SignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
