import type { NormalizedOperation } from './utils/parseSpec';
import { deriveFnName, fnNamePascal } from './utils/fnName';

const HEADER = `/* eslint-disable */
/**
 * @generated by @bombom/oas-gen
 * Do not edit by hand — run \`pnpm web:gen:api\`.
 */
`;

const BASE_PATH_STRIP = /^\/api\/v1/;

const stripBasePath = (p: string) => p.replace(BASE_PATH_STRIP, '');

const pathToTemplate = (p: string) =>
  p.replace(/\{([^}]+)\}/g, (_, name) => `\${${name}}`);

const hasBacktickPlaceholder = (p: string) => /\{[^}]+\}/.test(p);

type HttpMethod = NormalizedOperation['method'];

const fetcherMethod: Record<HttpMethod, string> = {
  get: 'fetcher.get',
  post: 'fetcher.post',
  patch: 'fetcher.patch',
  put: 'fetcher.put',
  delete: 'fetcher.delete',
};

const responseTypeAlias = (op: NormalizedOperation): string =>
  `${fnNamePascal(op)}Response`;
const queryTypeAlias = (op: NormalizedOperation): string =>
  `${fnNamePascal(op)}Query`;
const pathTypeAlias = (op: NormalizedOperation): string =>
  `${fnNamePascal(op)}Path`;
const bodyTypeAlias = (op: NormalizedOperation): string =>
  `${fnNamePascal(op)}Body`;

type GeneratedOp = {
  aliases: string[];
  fn: string;
};

const buildResponseAlias = (op: NormalizedOperation): string | null => {
  if (!op.hasOkResponseBody) return null;
  return (
    `export type ${responseTypeAlias(op)} =\n` +
    `  NonNullable<operations['${op.operationId}']['responses']['200']['content']['application/json']>;\n`
  );
};

const buildParamAliases = (op: NormalizedOperation): string[] => {
  const aliases: string[] = [];
  const pathParams = op.parameters.filter((p) => p.in === 'path');
  const queryParams = op.parameters.filter((p) => p.in === 'query');

  if (pathParams.length > 0) {
    aliases.push(
      `export type ${pathTypeAlias(op)} =\n` +
        `  NonNullable<operations['${op.operationId}']['parameters']>['path'];\n`,
    );
  }
  if (queryParams.length > 0) {
    aliases.push(
      `export type ${queryTypeAlias(op)} =\n` +
        `  NonNullable<operations['${op.operationId}']['parameters']>['query'];\n`,
    );
  }
  if (op.hasRequestBody) {
    aliases.push(
      `export type ${bodyTypeAlias(op)} =\n` +
        `  NonNullable<operations['${op.operationId}']['requestBody']>['content']['application/json'];\n`,
    );
  }
  return aliases;
};

const buildArgList = (
  op: NormalizedOperation,
): {
  signature: string;
  destructuredVars: { pathVars: string[]; hasQuery: boolean; hasBody: boolean };
} => {
  const pathParams = op.parameters.filter((p) => p.in === 'path');
  const queryParams = op.parameters.filter((p) => p.in === 'query');
  const hasBody = op.hasRequestBody;
  const pathVars = pathParams.map((p) => p.name);

  const intersections: string[] = [];
  if (pathParams.length > 0) intersections.push(pathTypeAlias(op));
  if (queryParams.length > 0) intersections.push(queryTypeAlias(op));
  if (hasBody) intersections.push(bodyTypeAlias(op));

  if (intersections.length === 0) {
    return {
      signature: '()',
      destructuredVars: { pathVars: [], hasQuery: false, hasBody: false },
    };
  }

  const typeExpr = intersections.join(' & ');

  const patternParts: string[] = [];
  for (const p of pathVars) patternParts.push(p);
  if (queryParams.length > 0 && hasBody) {
    patternParts.push('...rest');
  } else if (queryParams.length > 0) {
    patternParts.push('...query');
  } else if (hasBody) {
    patternParts.push('...body');
  }

  const pattern =
    patternParts.length > 0 ? `{ ${patternParts.join(', ')} }` : '_';
  return {
    signature: `(${pattern}: ${typeExpr})`,
    destructuredVars: {
      pathVars,
      hasQuery: queryParams.length > 0,
      hasBody,
    },
  };
};

const buildFetcherCall = (
  op: NormalizedOperation,
  destructured: { pathVars: string[]; hasQuery: boolean; hasBody: boolean },
): string => {
  const pathLiteral = (() => {
    const stripped = stripBasePath(op.path);
    if (hasBacktickPlaceholder(stripped)) {
      return `\`${pathToTemplate(stripped)}\``;
    }
    return `'${stripped}'`;
  })();

  const opts: string[] = [`path: ${pathLiteral}`];
  if (destructured.hasQuery) opts.push('query');
  if (destructured.hasBody) opts.push('body');

  const fetcher = fetcherMethod[op.method];
  const respType = op.hasOkResponseBody
    ? `<${responseTypeAlias(op)}>`
    : op.method === 'get'
      ? '<void>'
      : op.method === 'post' || op.method === 'patch' || op.method === 'put'
        ? `<${op.hasRequestBody ? bodyTypeAlias(op) : 'never'}, void>`
        : '<never, void>';

  return `  return ${fetcher}${respType}({ ${opts.join(', ')} });`;
};

const generateOp = (op: NormalizedOperation): GeneratedOp => {
  const aliases: string[] = [];
  const respAlias = buildResponseAlias(op);
  if (respAlias) aliases.push(respAlias);
  aliases.push(...buildParamAliases(op));

  const { signature, destructuredVars } = buildArgList(op);
  const body = buildFetcherCall(op, destructuredVars);

  const fn =
    `export const ${deriveFnName(op)} = async ${signature} => {\n` +
    `${body}\n` +
    `};\n`;

  return { aliases, fn };
};

export const generateApiFile = (
  _tag: string,
  ops: NormalizedOperation[],
): string => {
  const generated = ops.map(generateOp);
  const aliases = generated.flatMap((g) => g.aliases);
  const fns = generated.map((g) => g.fn);

  return (
    HEADER +
    `import { fetcher } from '../../fetcher';\n` +
    `import type { operations } from '../types';\n\n` +
    aliases.join('\n') +
    (aliases.length > 0 ? '\n' : '') +
    fns.join('\n')
  );
};
