import type { NormalizedOperation, ParameterObject } from './utils/parseSpec';

const HEADER = `/* eslint-disable */
/**
 * @generated by @bombom/oas-gen
 * Do not edit by hand — run \`pnpm web:generate-openapi-types\`.
 */
`;

const BASE_PATH_STRIP = /^\/api\/v1/;

const stripBasePath = (p: string) => p.replace(BASE_PATH_STRIP, '');

// "/articles/{id}/stats" → "/articles/${id}/stats"
const pathToTemplate = (p: string) =>
  p.replace(/\{([^}]+)\}/g, (_, name) => `\${${name}}`);

const hasBacktickPlaceholder = (p: string) => /\{[^}]+\}/.test(p);

type HttpMethod = NormalizedOperation['method'];

const fetcherMethod: Record<HttpMethod, string> = {
  get: 'fetcher.get',
  post: 'fetcher.post',
  patch: 'fetcher.patch',
  put: 'fetcher.put',
  delete: 'fetcher.delete',
};

const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

const responseTypeAlias = (op: NormalizedOperation): string =>
  `${capitalize(op.operationId)}Response`;
const queryTypeAlias = (op: NormalizedOperation): string =>
  `${capitalize(op.operationId)}Query`;
const pathTypeAlias = (op: NormalizedOperation): string =>
  `${capitalize(op.operationId)}Path`;
const bodyTypeAlias = (op: NormalizedOperation): string =>
  `${capitalize(op.operationId)}Body`;

type GeneratedOp = {
  /** Type alias declarations to emit at the top of the file. */
  aliases: string[];
  /** The function declaration. */
  fn: string;
  /** Which operations-keyed type buckets this op touches; used to verify operations[id] exists. */
};

const buildResponseAlias = (op: NormalizedOperation): string | null => {
  if (!op.hasOkResponseBody) return null;
  // We always reference the 200 response body for the alias. If the spec
  // documents the success case under 201 only, parseSpec currently keeps
  // hasOkResponseBody=true but the alias would resolve to `never`. That
  // edge case will be addressed once we have an operation that needs it.
  return (
    `export type ${responseTypeAlias(op)} =\n` +
    `  NonNullable<operations['${op.operationId}']['responses']['200']['content']['application/json']>;\n`
  );
};

const buildParamAliases = (op: NormalizedOperation): string[] => {
  const aliases: string[] = [];
  const pathParams = op.parameters.filter((p) => p.in === 'path');
  const queryParams = op.parameters.filter((p) => p.in === 'query');

  if (pathParams.length > 0) {
    aliases.push(
      `export type ${pathTypeAlias(op)} =\n` +
        `  NonNullable<operations['${op.operationId}']['parameters']>['path'];\n`,
    );
  }
  if (queryParams.length > 0) {
    aliases.push(
      `export type ${queryTypeAlias(op)} =\n` +
        `  NonNullable<operations['${op.operationId}']['parameters']>['query'];\n`,
    );
  }
  if (op.requestBodySchemaRef || op.method !== 'get') {
    // For non-GET methods with a JSON body, emit a body alias only when the
    // spec actually declares a requestBody schema.
    if (op.requestBodySchemaRef) {
      aliases.push(
        `export type ${bodyTypeAlias(op)} =\n` +
          `  NonNullable<operations['${op.operationId}']['requestBody']>['content']['application/json'];\n`,
      );
    }
  }
  return aliases;
};

const buildArgList = (op: NormalizedOperation): {
  signature: string;
  destructuredVars: { pathVars: string[]; hasQuery: boolean; hasBody: boolean };
} => {
  const pathParams = op.parameters.filter((p) => p.in === 'path');
  const queryParams = op.parameters.filter((p) => p.in === 'query');
  const hasBody = Boolean(op.requestBodySchemaRef);
  const pathVars = pathParams.map((p) => p.name);

  const intersections: string[] = [];
  if (pathParams.length > 0) intersections.push(pathTypeAlias(op));
  if (queryParams.length > 0) intersections.push(queryTypeAlias(op));
  if (hasBody) intersections.push(bodyTypeAlias(op));

  if (intersections.length === 0) {
    return {
      signature: '()',
      destructuredVars: { pathVars: [], hasQuery: false, hasBody: false },
    };
  }

  const typeExpr = intersections.join(' & ');

  // Build destructuring pattern
  const patternParts: string[] = [];
  for (const p of pathVars) patternParts.push(p);
  if (queryParams.length > 0 && hasBody) {
    // Distinguish body from query — fall back to passing the whole object;
    // the caller must split. To keep things simple we don't yet support both
    // in a single operation. Emit a TODO.
    patternParts.push('...rest');
  } else if (queryParams.length > 0) {
    patternParts.push('...query');
  } else if (hasBody) {
    patternParts.push('...body');
  }

  const pattern = patternParts.length > 0 ? `{ ${patternParts.join(', ')} }` : '_';
  return {
    signature: `(${pattern}: ${typeExpr})`,
    destructuredVars: {
      pathVars,
      hasQuery: queryParams.length > 0,
      hasBody,
    },
  };
};

const buildFetcherCall = (
  op: NormalizedOperation,
  destructured: { pathVars: string[]; hasQuery: boolean; hasBody: boolean },
): string => {
  const pathLiteral = (() => {
    const stripped = stripBasePath(op.path);
    if (hasBacktickPlaceholder(stripped)) {
      return `\`${pathToTemplate(stripped)}\``;
    }
    return `'${stripped}'`;
  })();

  const opts: string[] = [`path: ${pathLiteral}`];
  if (destructured.hasQuery) opts.push('query');
  if (destructured.hasBody) opts.push('body');

  const fetcher = fetcherMethod[op.method];
  const respType = op.hasOkResponseBody
    ? `<${responseTypeAlias(op)}>`
    : op.method === 'get'
      ? '<void>'
      : op.method === 'post' || op.method === 'patch' || op.method === 'put'
        ? `<${op.requestBodySchemaRef ? bodyTypeAlias(op) : 'never'}, void>`
        : '<never, void>';

  return `  return ${fetcher}${respType}({ ${opts.join(', ')} });`;
};

const generateOp = (op: NormalizedOperation): GeneratedOp => {
  const aliases: string[] = [];
  const respAlias = buildResponseAlias(op);
  if (respAlias) aliases.push(respAlias);
  aliases.push(...buildParamAliases(op));

  const { signature, destructuredVars } = buildArgList(op);
  const body = buildFetcherCall(op, destructuredVars);

  const fn =
    `export const ${op.operationId} = async ${signature} => {\n` +
    `${body}\n` +
    `};\n`;

  return { aliases, fn };
};

export const generateApiFile = (
  tag: string,
  ops: NormalizedOperation[],
): string => {
  const generated = ops.map(generateOp);
  const aliases = generated.flatMap((g) => g.aliases);
  const fns = generated.map((g) => g.fn);

  return (
    HEADER +
    `import { fetcher } from '@bombom/shared/apis';\n` +
    `import type { operations } from '@/types/openapi-spec';\n\n` +
    aliases.join('\n') +
    (aliases.length > 0 ? '\n' : '') +
    fns.join('\n')
  );
};
