const HEADER = `/* eslint-disable */
/**
 * @generated by @bombom/oas-gen
 * Do not edit by hand — run \`pnpm web:gen:api\`.
 */
`;

export const generateTagIndexFile = (tag: string, hasQuery: boolean): string => {
  const lowerTag = tag.toLowerCase();
  const lines = [`export * from './${lowerTag}.api';`];
  if (hasQuery) lines.push(`export * from './${lowerTag}.query';`);
  return HEADER + lines.join('\n') + '\n';
};
