import type { NormalizedOperation } from './utils/parseSpec';
import { isPageable } from './utils/detectPageable';
import { deriveFnName } from './utils/fnName';
import { toLowerCamel } from './utils/naming';

const HEADER = `/* eslint-disable */
/**
 * @generated by @bombom/oas-gen
 * Do not edit by hand — run \`pnpm web:generate-openapi-types\`.
 */
`;

const hasArgs = (op: NormalizedOperation): boolean => {
  const pathParams = op.parameters.filter((p) => p.in === 'path');
  const queryParams = op.parameters.filter((p) => p.in === 'query');
  return (
    pathParams.length > 0 ||
    queryParams.length > 0 ||
    Boolean(op.requestBodySchemaRef)
  );
};

const buildArgList = (op: NormalizedOperation, fnName: string): string =>
  hasArgs(op) ? `params: Parameters<typeof ${fnName}>[0]` : '';

const buildCallArgs = (op: NormalizedOperation): string =>
  hasArgs(op) ? 'params' : '';

const buildQueryKey = (
  tag: string,
  op: NormalizedOperation,
  variant?: 'infinite',
): string => {
  const base: string[] = [`'${tag.toLowerCase()}'`, `'${op.operationId}'`];
  if (variant === 'infinite') base.push(`'infinite'`);
  if (hasArgs(op)) base.push('params');
  return `[${base.join(', ')}]`;
};

export const generateQueryFile = (
  tag: string,
  ops: NormalizedOperation[],
): string | null => {
  const getOps = ops.filter((op) => op.method === 'get');
  if (getOps.length === 0) return null;

  const lowerTag = toLowerCamel(tag);
  const usesInfinite = getOps.some(isPageable);

  const queryImports = ['queryOptions'];
  if (usesInfinite) queryImports.push('infiniteQueryOptions');

  const fnImports = getOps.map((op) => deriveFnName(op));

  const entries: string[] = [];
  for (const op of getOps) {
    const fnName = deriveFnName(op);
    const argDecl = buildArgList(op, fnName);
    const callArgs = buildCallArgs(op);
    const arrow = argDecl ? `(${argDecl})` : '()';
    const queryKey = buildQueryKey(tag, op);
    entries.push(
      `  ${op.operationId}: ${arrow} =>\n` +
        `    queryOptions({\n` +
        `      queryKey: ${queryKey},\n` +
        `      queryFn: () => ${fnName}(${callArgs}),\n` +
        `    }),`,
    );

    if (isPageable(op)) {
      const infiniteKey = buildQueryKey(tag, op, 'infinite');
      entries.push(
        `  ${op.operationId}Infinite: ${arrow} =>\n` +
          `    infiniteQueryOptions({\n` +
          `      queryKey: ${infiniteKey},\n` +
          `      queryFn: ({ pageParam = 0 }) =>\n` +
          `        ${fnName}({\n` +
          `          ...(params as object),\n` +
          `          page: pageParam,\n` +
          `        } as Parameters<typeof ${fnName}>[0]),\n` +
          `      getNextPageParam: (lastPage: any) => {\n` +
          `        if (!lastPage || lastPage.last) return undefined;\n` +
          `        return (lastPage.number ?? 0) + 1;\n` +
          `      },\n` +
          `      initialPageParam: 0,\n` +
          `    }),`,
      );
    }
  }

  return (
    HEADER +
    `import { ${queryImports.join(', ')} } from '@tanstack/react-query';\n` +
    `import { ${fnImports.join(', ')} } from './${tag.toLowerCase()}.api';\n\n` +
    `export const ${lowerTag}Queries = {\n` +
    entries.join('\n') +
    `\n};\n`
  );
};
