import { readdir, readFile, writeFile, mkdir, rm, stat } from 'node:fs/promises';
import path from 'node:path';

const API_HEADER = `/* eslint-disable */
/**
 * @generated by @bombom/oas-gen (orval)
 * Do not edit by hand — run \`pnpm web:generate-openapi-types\`.
 */
`;

const SHARED_MUTATOR_IMPORT = `import { orvalMutator } from '@bombom/shared/apis';`;

// Rewrites the relative path orval uses for the mutator (e.g.
// `../../../shared/src/core/apis/orvalMutator`) into our public package
// entrypoint, so the generated file is portable.
const rewriteImports = (code: string): string => {
  const importRegex =
    /import\s+\{\s*orvalMutator[\s,]*\}\s+from\s+['"][^'"]+orvalMutator['"];?/m;
  if (importRegex.test(code)) {
    return code.replace(importRegex, SHARED_MUTATOR_IMPORT);
  }
  return code;
};

const isApiFile = (file: string) =>
  file.endsWith('.ts') && !file.endsWith('.schemas.ts') && !file.endsWith('.msw.ts');

/**
 * Moves orval's tag-split output (e.g. `_tmp/pet/pet.ts`) into our
 * domain convention (`web/src/apis/pet/pet.api.ts`), prepends an
 * @generated header, and rewrites the mutator import to a package import.
 *
 * Returns the list of tag folder names that were emitted.
 */
export const postProcessOrvalOutput = async (
  tmpDir: string,
  apisDir: string,
): Promise<string[]> => {
  const emittedTags: string[] = [];

  let entries: string[];
  try {
    entries = await readdir(tmpDir);
  } catch {
    return emittedTags;
  }

  for (const entry of entries) {
    const entryPath = path.join(tmpDir, entry);
    const s = await stat(entryPath);
    if (!s.isDirectory()) continue;
    if (entry.startsWith('_')) continue; // skip `_models`

    const tagDirName = entry.toLowerCase();
    const tagFiles = await readdir(entryPath);

    for (const f of tagFiles) {
      if (!isApiFile(f)) continue;
      const baseName = path.basename(f, '.ts');
      const src = path.join(entryPath, f);
      const dest = path.join(apisDir, tagDirName, `${baseName}.api.ts`);

      let code = await readFile(src, 'utf-8');
      code = rewriteImports(code);
      code = API_HEADER + code;

      await mkdir(path.dirname(dest), { recursive: true });
      await writeFile(dest, code, 'utf-8');
    }
    emittedTags.push(tagDirName);
  }

  await rm(tmpDir, { recursive: true, force: true });
  return emittedTags;
};
