name: Frontend PR CI

on:
  pull_request:
    paths:
      - 'web/**'
      - 'shared/**'
      - '.github/workflows/frontend-*.yml'
      - 'pnpm-lock.yaml'
      - 'package.json'

jobs:
  pre-build:
    uses: ./.github/workflows/frontend-ci-base.yml
    with:
      run-build: false
