/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    DailyJoinedMembersResponse: {
      /** Format: date */
      date?: string;
      /** Format: int64 */
      count?: number;
    };
    DashboardStatsResponse: {
      /** Format: int64 */
      totalMembers?: number;
      /** Format: int64 */
      totalNotices?: number;
      /** Format: int64 */
      dailyJoinedMembers?: number;
      /** Format: int64 */
      weeklyJoinedMembers?: number;
      /** Format: int64 */
      monthlyJoinedMembers?: number;
      /** Format: int64 */
      yearlyJoinedMembers?: number;
      /** Format: int64 */
      withdrawnMembersThisMonth?: number;
      /** Format: int64 */
      todayActiveMembers?: number;
      dailyJoinedTrend?: components['schemas']['DailyJoinedMembersResponse'][];
      /** Format: date-time */
      aggregatedAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
