/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/admin/api/v1/notices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 공지사항 목록 조회
     * @description 공지사항 목록을 조회합니다. (검색어, 카테고리 필터링 지원)
     */
    get: operations['getNotices'];
    put?: never;
    /**
     * 공지사항 생성
     * @description 새로운 공지사항 또는 이벤트를 등록합니다.
     */
    post: operations['createNotice'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/newsletters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 뉴스레터 목록 조회
     * @description 뉴스레터 목록을 조회합니다. <br>- **검색**: 키워드로 이름, 설명, 발행 주기를 검색합니다. <br>- **필터**: 카테고리 이름으로 정확히 일치하는 뉴스레터를 필터링합니다. <br>- **정렬**: `LATEST`(최신순), `POPULAR`(인기순/구독자순) 정렬을 지원합니다.
     */
    get: operations['getNewsletters'];
    put?: never;
    /**
     * 뉴스레터 생성
     * @description 새로운 뉴스레터를 등록합니다.
     */
    post: operations['createNewsletter'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 파일 업로드
     * @description 파일을 업로드하고 URL을 반환합니다.
     */
    post: operations['upload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/challenges/{challengeId}/teams': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 챌린지 팀 목록 조회
     * @description 챌린지에 포함된 모든 팀 목록을 조회합니다.
     *
     *     **Frontend Tip:**
     *     - 수동 팀 배정 시 **팀 선택 드롭다운**을 구성하는 데 사용하세요.
     *     - `id` (팀 ID)와 `progress` (진행도) 정보를 제공합니다.
     *
     */
    get: operations['getChallengeTeams'];
    put?: never;
    /**
     * 챌린지 팀 일괄 생성
     * @description 지정된 개수만큼 챌린지 팀을 일괄 생성합니다.
     */
    post: operations['createChallengeTeams'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/challenges/{challengeId}/teams/assignment': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 챌린지 팀 자동 배정
     * @description 챌린지 참여자를 대상으로 팀을 자동으로 배정합니다.
     *     - 목표 팀원 수: 15명
     *     - 전체 참여자를 무작위로 섞은 후, 균등하게 배분합니다.
     *
     *     **Frontend Tip:**
     *     - 이미 팀이 배정된 상태에서 호출하면 **기존 배정이 초기화되고 재배정**됩니다. (주의 메시지 필요)
     *
     */
    post: operations['assignTeams'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/notices/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 공지사항 상세 조회
     * @description 공지사항 상세 정보를 조회합니다.
     */
    get: operations['getNotice'];
    put?: never;
    post?: never;
    /**
     * 공지사항 삭제
     * @description 기존 공지사항을 삭제합니다.
     */
    delete: operations['deleteNotice'];
    options?: never;
    head?: never;
    /**
     * 공지사항 수정
     * @description 기존 공지사항을 수정합니다.
     */
    patch: operations['updateNotice'];
    trace?: never;
  };
  '/admin/api/v1/newsletters/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 뉴스레터 상세 조회
     * @description 뉴스레터 상세 정보를 조회합니다.
     */
    get: operations['getNewsletterDetail'];
    put?: never;
    post?: never;
    /**
     * 뉴스레터 삭제
     * @description 뉴스레터를 삭제합니다.
     */
    delete: operations['deleteNewsletter'];
    options?: never;
    head?: never;
    /**
     * 뉴스레터 수정
     * @description 뉴스레터 정보를 수정합니다.
     */
    patch: operations['updateNewsletter'];
    trace?: never;
  };
  '/admin/api/v1/members/{id}/role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 회원 권한 수정
     * @description 특정 회원의 권한(Role)을 수정합니다.
     */
    patch: operations['updateRole'];
    trace?: never;
  };
  '/admin/api/v1/challenges/{challengeId}/participants/{participantId}/team': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 챌린지 참여자 팀 변경
     * @description 챌린지 참여자의 팀을 수동으로 변경합니다.
     *
     *     **Frontend Tip:**
     *     - `challengeTeamId`는 반드시 **해당 챌린지에 속한 팀의 ID**여야 합니다. (팀 목록 조회 API 활용)
     *     - 유효하지 않은 팀 ID를 보낼 경우 `400 Bad Request` 에러가 발생하므로, 에러 메시지를 사용자에게 보여주세요.
     *
     */
    patch: operations['updateParticipantTeam'];
    trace?: never;
  };
  '/admin/api/v1/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 회원 목록 조회
     * @description 검색 조건에 맞는 회원 목록을 페이징하여 조회합니다.
     */
    get: operations['getMembers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/dashboard/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 대시보드 통계 조회
     * @description 전체 회원 수, 공지사항 수, 이번 달 신규 회원 수를 조회합니다.
     */
    get: operations['getStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/challenges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 챌린지 목록 조회
     * @description 챌린지 목록을 조회합니다.
     *
     *     - **status**: 챌린지 진행 상태 필터링 (BEFORE_START, ONGOING, COMPLETED)
     *     - **sort**: 정렬 기준 (기본값: id,DESC)
     *
     */
    get: operations['getChallenges'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/challenges/{challengeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 챌린지 단건 조회
     * @description 챌린지 상세 정보를 조회합니다.
     */
    get: operations['getChallenge'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/challenges/{challengeId}/participants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 챌린지 참여자 목록 조회
     * @description 챌린지 별 참여자 목록을 조회합니다.
     *
     *     **Frontend Tip:**
     *     - **teamId 필터링**: 특정 팀의 멤버만 보고 싶을 때 사용하세요.
     *     - **hasTeam 필터링**: `false`로 설정하면 '팀 미배정자'만 조회할 수 있습니다. (수동 배정 대상 찾기에 유용)
     *
     */
    get: operations['getChallengeParticipants'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/challenges/{challengeId}/teams/{teamId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 챌린지 팀 삭제
     * @description 챌린지 팀을 삭제합니다.
     *
     *     **Frontend Tip:**
     *     - 삭제 시 해당 팀에 속해있던 참여자들은 자동으로 **'팀 미배정'** 상태가 됩니다.
     *
     */
    delete: operations['deleteChallengeTeam'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateNoticeRequest: {
      title: string;
      content: string;
      /** @enum {string} */
      noticeCategory: 'NOTICE' | 'UPDATE' | 'EVENT' | 'CHECK';
    };
    CreateNewsletterRequest: {
      name: string;
      description: string;
      imageUrl: string;
      email: string;
      category: string;
      mainPageUrl: string;
      subscribeUrl: string;
      issueCycle: string;
      sender: string;
      previousNewsletterUrl?: string;
      subscribeMethod?: string;
    };
    UploadFileResponse: {
      url?: string;
    };
    CreateChallengeTeamsRequest: {
      /** Format: int32 */
      count: number;
    };
    AssignTeamsRequest: {
      /**
       * Format: int32
       * @description 팀 당 최대 인원 수 (기본값: 15)
       * @default 15
       * @example 15
       */
      maxTeamSize: number;
    };
    UpdateNoticeRequest: {
      title?: string;
      content?: string;
      /** @enum {string} */
      noticeCategory?: 'NOTICE' | 'UPDATE' | 'EVENT' | 'CHECK';
    };
    UpdateNewsletterRequest: {
      name?: string;
      description?: string;
      imageUrl?: string;
      email?: string;
      category?: string;
      mainPageUrl?: string;
      subscribeUrl?: string;
      issueCycle?: string;
      sender?: string;
      previousNewsletterUrl?: string;
      previousAllowed?: boolean;
      subscribeMethod?: string;
      /** @enum {string} */
      previousStrategy?:
        | 'FIXED_WITH_RECENT'
        | 'FIXED_ONLY'
        | 'RECENT_ONLY'
        | 'INACTIVE';
      /** Format: int32 */
      previousFixedCount?: number;
      /** Format: int32 */
      previousRecentCount?: number;
      /** Format: int32 */
      previousExposureRatio?: number;
    };
    UpdateRoleRequest: {
      authority: string;
    };
    UpdateParticipantTeamRequest: {
      /** Format: int64 */
      challengeTeamId: number;
    };
    GetNoticeResponse: {
      /** Format: int64 */
      id?: number;
      title?: string;
      noticeCategory?: string;
      /** Format: date */
      createdAt?: string;
    };
    PageGetNoticeResponse: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['GetNoticeResponse'][];
      /** Format: int32 */
      number?: number;
      sort?: components['schemas']['SortObject'];
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      first?: boolean;
      last?: boolean;
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components['schemas']['SortObject'];
      paged?: boolean;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
      unpaged?: boolean;
    };
    SortObject: {
      empty?: boolean;
      sorted?: boolean;
      unsorted?: boolean;
    };
    GetNoticeDetailResponse: {
      title?: string;
      /** @enum {string} */
      noticeCategory?: 'NOTICE' | 'UPDATE' | 'EVENT' | 'CHECK';
      content?: string;
      /** Format: date */
      createdAt?: string;
    };
    GetNewsletterSummaryResponse: {
      /** Format: int64 */
      id?: number;
      name?: string;
      imageUrl?: string;
      categoryName?: string;
      issueCycle?: string;
      /** Format: int32 */
      subscriptionCount?: number;
      previousStrategy?: string;
    };
    GetNewsletterResponse: {
      /** Format: int64 */
      id?: number;
      name?: string;
      description?: string;
      imageUrl?: string;
      email?: string;
      categoryName?: string;
      mainPageUrl?: string;
      subscribeUrl?: string;
      issueCycle?: string;
      /** Format: int32 */
      subscriptionCount?: number;
      sender?: string;
      previousNewsletterUrl?: string;
      previousAllowed?: boolean;
      subscribeMethod?: string;
      previousStrategy?: string;
      /** Format: int32 */
      previousFixedCount?: number;
      /** Format: int32 */
      previousRecentCount?: number;
      /** Format: int32 */
      previousExposureRatio?: number;
    };
    MembersOptionsRequest: {
      name?: string;
      role?: string;
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    GetMemberResponse: {
      /** Format: int64 */
      id?: number;
      nickname?: string;
      email?: string;
      role?: string;
    };
    PageGetMemberResponse: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['GetMemberResponse'][];
      /** Format: int32 */
      number?: number;
      sort?: components['schemas']['SortObject'];
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      first?: boolean;
      last?: boolean;
      empty?: boolean;
    };
    DashboardStatsResponse: {
      /** Format: int64 */
      totalMembers?: number;
      /** Format: int64 */
      totalNotices?: number;
      /** Format: int64 */
      dailyJoinedMembers?: number;
      /** Format: int64 */
      weeklyJoinedMembers?: number;
      /** Format: int64 */
      monthlyJoinedMembers?: number;
      /** Format: int64 */
      yearlyJoinedMembers?: number;
      /** Format: int64 */
      withdrawnMembersThisMonth?: number;
    };
    GetChallengeResponse: {
      /** Format: int64 */
      id?: number;
      name?: string;
      /** Format: int32 */
      generation?: number;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
    };
    PageGetChallengeResponse: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['GetChallengeResponse'][];
      /** Format: int32 */
      number?: number;
      sort?: components['schemas']['SortObject'];
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      first?: boolean;
      last?: boolean;
      empty?: boolean;
    };
    GetChallengeDetailResponse: {
      /** Format: int64 */
      id?: number;
      name?: string;
      /** Format: int32 */
      generation?: number;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
    };
    GetChallengeTeamResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      challengeId?: number;
      /** Format: int32 */
      progress?: number;
    };
    GetChallengeParticipantResponse: {
      /** Format: int64 */
      participantId?: number;
      nickname?: string;
      /** Format: int64 */
      challengeTeamId?: number;
      /** Format: int32 */
      completedDays?: number;
      isSurvived?: boolean;
    };
    PageGetChallengeParticipantResponse: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['GetChallengeParticipantResponse'][];
      /** Format: int32 */
      number?: number;
      sort?: components['schemas']['SortObject'];
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      first?: boolean;
      last?: boolean;
      empty?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getNotices: {
    parameters: {
      query?: {
        keyword?: string;
        category?: 'NOTICE' | 'UPDATE' | 'EVENT' | 'CHECK';
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageGetNoticeResponse'];
        };
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createNotice: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description noticeCategory: [NOTICE, UPDATE, EVENT, CHECK] 중 하나 선택 */
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNoticeRequest'];
      };
    };
    responses: {
      /** @description 공지사항 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 잘못된 요청 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getNewsletters: {
    parameters: {
      query?: {
        keyword?: string;
        category?: string;
        previousStrategy?:
          | 'FIXED_WITH_RECENT'
          | 'FIXED_ONLY'
          | 'RECENT_ONLY'
          | 'INACTIVE';
        sort?: 'LATEST' | 'POPULAR';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['GetNewsletterSummaryResponse'][];
        };
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createNewsletter: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNewsletterRequest'];
      };
    };
    responses: {
      /** @description 뉴스레터 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 잘못된 요청 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  upload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          /**
           * Format: binary
           * @description 업로드할 파일
           */
          file: string;
        };
      };
    };
    responses: {
      /** @description 업로드 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UploadFileResponse'];
        };
      };
      /** @description 잘못된 요청 (파일 없음 등) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 업로드 실패 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getChallengeTeams: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 챌린지 ID */
        challengeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['GetChallengeTeamResponse'][];
        };
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 챌린지 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createChallengeTeams: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 챌린지 ID */
        challengeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateChallengeTeamsRequest'];
      };
    };
    responses: {
      /** @description 생성 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 챌린지 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  assignTeams: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 챌린지 ID */
        challengeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssignTeamsRequest'];
      };
    };
    responses: {
      /** @description 배정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 챌린지 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getNotice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 조회할 공지사항 ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['GetNoticeDetailResponse'];
        };
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 공지사항 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteNotice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 삭제할 공지사항 ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공지사항 삭제 성공 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 잘못된 요청 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateNotice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 수정할 공지사항 ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNoticeRequest'];
      };
    };
    responses: {
      /** @description 공지사항 수정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 공지사항 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getNewsletterDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['GetNewsletterResponse'];
        };
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 뉴스레터를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteNewsletter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 삭제 성공 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 뉴스레터를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateNewsletter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNewsletterRequest'];
      };
    };
    responses: {
      /** @description 수정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 뉴스레터를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 회원 ID
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    /** @description authority: [ADMIN, USER] 중 하나 선택 */
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRoleRequest'];
      };
    };
    responses: {
      /** @description 회원 권한 수정 성공 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 잘못된 요청 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 회원을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateParticipantTeam: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 챌린지 ID */
        challengeId: number;
        /** @description 참여자 ID (Member ID) */
        participantId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateParticipantTeamRequest'];
      };
    };
    responses: {
      /** @description 변경 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 잘못된 입력 (유효하지 않은 팀, 현재 팀과 동일 등) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 챌린지/팀/참여자 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getMembers: {
    parameters: {
      query: {
        /** @description 검색 옵션 (role: [ADMIN, USER], name: 이름 검색) */
        query: components['schemas']['MembersOptionsRequest'];
        /** @description 페이징 관련 요청 (예: ?page=0&size=20) */
        pageable: components['schemas']['Pageable'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 회원 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageGetMemberResponse'];
        };
      };
      /** @description 잘못된 요청 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getStats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 통계 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['DashboardStatsResponse'];
        };
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getChallenges: {
    parameters: {
      query?: {
        status?: 'BEFORE_START' | 'ONGOING' | 'COMPLETED';
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageGetChallengeResponse'];
        };
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 챌린지 ID */
        challengeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['GetChallengeDetailResponse'];
        };
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 챌린지 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getChallengeParticipants: {
    parameters: {
      query?: {
        challengeTeamId?: number;
        hasTeam?: boolean;
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path: {
        /** @description 챌린지 ID */
        challengeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageGetChallengeParticipantResponse'];
        };
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 챌린지 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteChallengeTeam: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 챌린지 ID */
        challengeId: number;
        /** @description 챌린지 팀 ID */
        teamId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 삭제 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 챌린지/팀 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
