/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/admin/api/v1/notices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 공지사항 목록 조회
     * @description 공지사항 목록을 조회합니다. (검색어, 카테고리 필터링 지원)
     */
    get: operations['getNotices'];
    put?: never;
    /**
     * 공지사항 생성
     * @description 새로운 공지사항 또는 이벤트를 등록합니다.
     */
    post: operations['createNotice'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/newsletters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 뉴스레터 목록 조회
     * @description 뉴스레터 목록을 조회합니다. <br>- **검색**: 키워드로 이름, 설명, 발행 주기를 검색합니다. <br>- **필터**: 카테고리 이름으로 정확히 일치하는 뉴스레터를 필터링합니다. <br>- **정렬**: `LATEST`(최신순), `POPULAR`(인기순/구독자순) 정렬을 지원합니다.
     */
    get: operations['getNewsletters'];
    put?: never;
    /**
     * 뉴스레터 생성
     * @description 새로운 뉴스레터를 등록합니다.
     */
    post: operations['createNewsletter'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/api/v1/notices/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 공지사항 상세 조회
     * @description 공지사항 상세 정보를 조회합니다.
     */
    get: operations['getNotice'];
    put?: never;
    post?: never;
    /**
     * 공지사항 삭제
     * @description 기존 공지사항을 삭제합니다.
     */
    delete: operations['deleteNotice'];
    options?: never;
    head?: never;
    /**
     * 공지사항 수정
     * @description 기존 공지사항을 수정합니다.
     */
    patch: operations['updateNotice'];
    trace?: never;
  };
  '/admin/api/v1/newsletters/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 뉴스레터 상세 조회
     * @description 뉴스레터 상세 정보를 조회합니다.
     */
    get: operations['getNewsletterDetail'];
    put?: never;
    post?: never;
    /**
     * 뉴스레터 삭제
     * @description 뉴스레터를 삭제합니다.
     */
    delete: operations['deleteNewsletter'];
    options?: never;
    head?: never;
    /**
     * 뉴스레터 수정
     * @description 뉴스레터 정보를 수정합니다.
     */
    patch: operations['updateNewsletter'];
    trace?: never;
  };
  '/admin/api/v1/members/{id}/role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 회원 권한 수정
     * @description 특정 회원의 권한(Role)을 수정합니다.
     */
    patch: operations['updateRole'];
    trace?: never;
  };
  '/admin/api/v1/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 회원 목록 조회
     * @description 검색 조건에 맞는 회원 목록을 페이징하여 조회합니다.
     */
    get: operations['getMembers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateNoticeRequest: {
      title: string;
      content: string;
      /** @enum {string} */
      noticeCategory: 'NOTICE' | 'UPDATE' | 'EVENT' | 'CHECK';
    };
    CreateNewsletterRequest: {
      name: string;
      description: string;
      imageUrl: string;
      email: string;
      category: string;
      mainPageUrl: string;
      subscribeUrl: string;
      issueCycle: string;
      sender: string;
      previousNewsletterUrl?: string;
      subscribeMethod?: string;
    };
    UpdateNoticeRequest: {
      title?: string;
      content?: string;
      /** @enum {string} */
      noticeCategory?: 'NOTICE' | 'UPDATE' | 'EVENT' | 'CHECK';
    };
    UpdateNewsletterRequest: {
      name?: string;
      description?: string;
      imageUrl?: string;
      email?: string;
      category?: string;
      mainPageUrl?: string;
      subscribeUrl?: string;
      issueCycle?: string;
      sender?: string;
      previousNewsletterUrl?: string;
      previousAllowed?: boolean;
      subscribeMethod?: string;
      /** @enum {string} */
      previousStrategy?:
        | 'FIXED_WITH_RECENT'
        | 'FIXED_ONLY'
        | 'RECENT_ONLY'
        | 'INACTIVE';
      /** Format: int32 */
      previousFixedCount?: number;
      /** Format: int32 */
      previousRecentCount?: number;
      /** Format: int32 */
      previousExposureRatio?: number;
    };
    UpdateRoleRequest: {
      authority: string;
    };
    GetNoticeResponse: {
      /** Format: int64 */
      id?: number;
      title?: string;
      noticeCategory?: string;
      /** Format: date */
      createdAt?: string;
    };
    PageGetNoticeResponse: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['GetNoticeResponse'][];
      /** Format: int32 */
      number?: number;
      sort?: components['schemas']['SortObject'];
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      first?: boolean;
      last?: boolean;
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components['schemas']['SortObject'];
      paged?: boolean;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
      unpaged?: boolean;
    };
    SortObject: {
      empty?: boolean;
      sorted?: boolean;
      unsorted?: boolean;
    };
    GetNoticeDetailResponse: {
      title?: string;
      /** @enum {string} */
      noticeCategory?: 'NOTICE' | 'UPDATE' | 'EVENT' | 'CHECK';
      content?: string;
      /** Format: date */
      createdAt?: string;
    };
    GetNewsletterSummaryResponse: {
      /** Format: int64 */
      id?: number;
      name?: string;
      imageUrl?: string;
      categoryName?: string;
      issueCycle?: string;
      /** Format: int32 */
      subscriptionCount?: number;
      previousStrategy?: string;
    };
    GetNewsletterResponse: {
      /** Format: int64 */
      id?: number;
      name?: string;
      description?: string;
      imageUrl?: string;
      email?: string;
      categoryName?: string;
      mainPageUrl?: string;
      subscribeUrl?: string;
      issueCycle?: string;
      /** Format: int32 */
      subscriptionCount?: number;
      sender?: string;
      previousNewsletterUrl?: string;
      previousAllowed?: boolean;
      subscribeMethod?: string;
      previousStrategy?: string;
      /** Format: int32 */
      previousFixedCount?: number;
      /** Format: int32 */
      previousRecentCount?: number;
      /** Format: int32 */
      previousExposureRatio?: number;
    };
    MembersOptionsRequest: {
      name?: string;
      role?: string;
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    GetMemberResponse: {
      /** Format: int64 */
      id?: number;
      nickname?: string;
      email?: string;
      role?: string;
    };
    PageGetMemberResponse: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['GetMemberResponse'][];
      /** Format: int32 */
      number?: number;
      sort?: components['schemas']['SortObject'];
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      first?: boolean;
      last?: boolean;
      empty?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getNotices: {
    parameters: {
      query?: {
        keyword?: string;
        category?: 'NOTICE' | 'UPDATE' | 'EVENT' | 'CHECK';
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageGetNoticeResponse'];
        };
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createNotice: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description noticeCategory: [NOTICE, UPDATE, EVENT, CHECK] 중 하나 선택 */
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNoticeRequest'];
      };
    };
    responses: {
      /** @description 공지사항 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 잘못된 요청 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getNewsletters: {
    parameters: {
      query?: {
        keyword?: string;
        category?: string;
        previousStrategy?:
          | 'FIXED_WITH_RECENT'
          | 'FIXED_ONLY'
          | 'RECENT_ONLY'
          | 'INACTIVE';
        sort?: 'LATEST' | 'POPULAR';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['GetNewsletterSummaryResponse'][];
        };
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createNewsletter: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNewsletterRequest'];
      };
    };
    responses: {
      /** @description 뉴스레터 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 잘못된 요청 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getNotice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 조회할 공지사항 ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['GetNoticeDetailResponse'];
        };
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 공지사항 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteNotice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 삭제할 공지사항 ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공지사항 삭제 성공 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 잘못된 요청 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateNotice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 수정할 공지사항 ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNoticeRequest'];
      };
    };
    responses: {
      /** @description 공지사항 수정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 존재하지 않는 공지사항 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getNewsletterDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['GetNewsletterResponse'];
        };
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 뉴스레터를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteNewsletter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 삭제 성공 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 뉴스레터를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateNewsletter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNewsletterRequest'];
      };
    };
    responses: {
      /** @description 수정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 뉴스레터를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 회원 ID
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    /** @description authority: [ADMIN, USER] 중 하나 선택 */
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRoleRequest'];
      };
    };
    responses: {
      /** @description 회원 권한 수정 성공 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 잘못된 요청 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 회원을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getMembers: {
    parameters: {
      query: {
        /** @description 검색 옵션 (role: [ADMIN, USER], name: 이름 검색) */
        query: components['schemas']['MembersOptionsRequest'];
        /** @description 페이징 관련 요청 (예: ?page=0&size=20) */
        pageable: components['schemas']['Pageable'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 회원 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageGetMemberResponse'];
        };
      };
      /** @description 잘못된 요청 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증 실패 (로그인 필요) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
